services:
  - docker

before_deploy: 
  - docker build -t tradeforgoals.azurecr.io/tradeforgoals/backend ./tradeforgoals 

deploy:
  provider: script
  script: bash ./tradeforgoals/docker_push
  on:
    branch: master
