language: node_js

node_js:
  - "stable"

services:
  - docker

before_deploy: 
  - docker build -t tradeforgoals.azurecr.io/tradeforgoals/backend ./tradeforgoals 

deploy:
  provider: script
  script: bash ./tradeforgoals/docker_push
  on:
    branch: master

addons:
  sonarcloud:
    organization: "tradeforgoals"
    token:
      secure: "$SONAR_TOKEN"
script:
  - mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io
